# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 0.83.0"
gem "rubocop-github", "~> 0.16.1"
gem "rubocop-performance", "~> 1.8.0"
gem "rubocop-rails", "~> 2.7", ">= 2.7.0"
gem "rubocop-rspec", "~> 1.42.0"
